name: Train-Pipeline

on:
  push:
    branches:
    - branch_01

jobs:
  train_pipeline:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v1
            with:
              fetch-depth: 0

          - name: Set up Python 3.9
            uses: actions/setup-python@v1
            with:
                python-version: 3.9

          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

          - name: Train Model
            run: |
              python train.py